0515-dragons/config/routes.rb
Dragons::Application.routes.draw do
  resources :users, only: [:new, :create]
  resources :dragons

  resources :sessions
  root 'dragons#index'

  resources :emails, only: [:new, :create]

  post 'emails/emailform' => 'emails#create'

  

end

0515-dragons/app/models/dragon.rb
class Dragon
  include Mongoid::Document
  field :name, type: String
  field :size, type: String
  field :color, type: String
  field :age, type: Integer
  field :is_firebreathing, type: Boolean

  belongs_to :user
end

0515-dragons/app/models/email.rb
class Email
  include Mongoid::Document
  field :name, type: String
  field :address, type: String
end

0515-dragons/app/models/user.rb
require 'bcrypt'

class User
  include Mongoid::Document
  field :name, type: String
  field :email, type: String
  field :password_digest, type: String

  has_many :dragons

  def password
    @password
  end

  def password=(new_password)
    @password = new_password
    self.password_digest = BCrypt::Password.create(new_password)
  end

  def authenticate(test_password)
    if BCrypt::Password.new(self.password_digest) == test_password
      self
    else
      false
    end
  end
  
end

0515-dragons/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  include ApplicationHelper
end

0515-dragons/app/controllers/dragons_controller.rb
class DragonsController < ApplicationController
  before_action :authenticate_user

  def index
  	@dragons = Dragon.all
  end

  def new
    @user = current_user
  	@dragon = Dragon.new
    
  end

  def create
    @user = current_user
  	@dragon = current_user.dragons.new(params.require(:dragon).permit(:name, :size, :color, :age, :is_firebreathing))
  	if @dragon.save
  		redirect_to dragon_path(@dragon)
  	else
  		flash[:error] = "The egg didn't hatch. Try again."
  		render 'new'
  	end
  end

  def show
  	@dragon = Dragon.find(params[:id])
  end

  def edit
    @dragon = Dragon.find(params[:id])
  end

  def update
  end

  def destroy
    Dragon.find(params[:id]).destroy
    redirect_to dragons_path
  end


  private
  def verify_logged_in
    if !current_user
      flash[:error] = "You must log in before you can see the dragons!"
      redirect_to new_session_path
    end
  end

end

0515-dragons/app/controllers/emails_controller.rb
class EmailsController < ApplicationController

	def new
		@email = Email.new
	end

	def create
		@email = Email.new(params.require(:email).permit(:name, :address))
		if @email.save
			Mailer.welcome(@email).deliver
			redirect_to :back
		else
			render 'emailform'
		end
	end

end

0515-dragons/app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
	def new
  end

  def create
    @user = User.where(:email => params[:session][:email]).first

    if @user == nil || !@user.authenticate(params[:session][:password])
      flash[:error] = "Invalid email/password combination"
      render 'new'
    else
      session[:remember_token] = @user.id
      @current_user = @user
      redirect_to root_path
    end

  end

  def destroy
    session.delete(:remember_token)
    redirect_to root_path
  end

end

0515-dragons/app/controllers/users_controller.rb
class UsersController < ApplicationController
  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)
    if @user.save
      flash[:success] = "You have signed up successfully"
      redirect_to :root
    else
      render :new
    end
  end

  protected

  def user_params
    params.require(:user).permit(:name, :email, :password)
  end
end

0515-dragons/app/helpers/application_helper.rb
module ApplicationHelper

  def current_user
    @current_user ||= session[:remember_token] && User.find(session[:remember_token])
  end

  def authenticate_user
    if !current_user
      redirect_to new_session_path
    end
  end

end

0515-dragons/app/helpers/dragons_helper.rb
module DragonsHelper
end

0515-dragons/app/helpers/emails_helper.rb
module EmailsHelper
end

0515-dragons/app/helpers/sessions_helper.rb
module SessionsHelper
end

0515-dragons/app/helpers/users_helper.rb
module UsersHelper
end

0515-dragons/app/views/dragons/index.html.erb
<h1>Here there be DRAGONS</h1>

<% @dragons.each do |d| %>
	<h2><%= d.name %></h2> <%= link_to "Learn about this dragon.", dragon_path(d) %>
<% end %>

<hr>
<%= link_to "Hatch a new dragon!", new_dragon_path %>

0515-dragons/app/views/dragons/new.html.erb
<h1> Hatch a new dragon! </h1>

<%= form_for @dragon do |f| %>
	<%= f.label :name %>
	<%= f.text_field :name %>
	<%= f.label :size %>
  <%= f.text_field :size %>
  <%= f.label :color %>
  <%= f.text_field :color %>
  <%= f.label :age %>
  <%= f.text_field :age %>
  <%= f.label :if_firebreathing %>
  <%= f.check_box :is_firebreathing %>
	<%= f.submit %>
<% end %>

0515-dragons/app/views/dragons/show.html.erb
<h1> <%= @dragon.name %> </h1>

<p><%= @dragon.name %> is a <%= @dragon.size %> <%= @dragon.color %> dragon who is <%= @dragon.age %> years old.</p>
<% if @dragon.is_firebreathing == true %>
<p>This dragon is dangerous and breathes fire.</p>
<% end %>

<% if @dragon.user == current_user %>
<p>This is my dragon!</p>
<% end %>

<%= link_to "Kill this dragon", dragon_path, method: "delete" %>