0512-burrito-upgrade-part-2/config/routes.rb
BurritoApp::Application.routes.draw do
  resource :sessions, only: [:new, :create, :destroy]
  resources :users, only: [:new, :create]
  resources :ingredients, except: [:destroy]
  resources :burritos, except: [:destroy]

  root 'burritos#index'

end

0512-burrito-upgrade-part-2/app/models/burrito.rb
class Burrito
  include Mongoid::Document
  field :name, type: String

  has_many :burrito_ingredients

  # Fakes out a has_many :through

  # First the objects
  def ingredients
    BurritoIngredient.where(burrito_id: id).map do |bi|
      bi.ingredient
    end
  end

  # Show all related ingredient IDs
  def ingredient_ids
    ingredients.map(&:id)
  end

  # Add and remove ingredients as necessary
  def ingredient_ids=(vals)
    my_bi = BurritoIngredient.where(burrito_id: self.id).map(&:ingredient_id)
    vals.each do |s|
      next if s.blank?
      s_id = BSON::ObjectId.from_string(s)
      if my_bi.include?(s_id)
        my_bi.delete(s_id)
      else
        BurritoIngredient.create(burrito_id: self.id, ingredient_id: s_id)
      end
    end
    my_bi.each do |r|
      BurritoIngredient.find_by(burrito_id: self.id, ingredient_id: r).destroy
    end
  end
end

0512-burrito-upgrade-part-2/app/models/burrito_ingredient.rb
class BurritoIngredient
  include Mongoid::Document
  belongs_to :burrito
  belongs_to :ingredient
end

0512-burrito-upgrade-part-2/app/models/ingredient.rb
class Ingredient
  include Mongoid::Document
  field :name, type: String

  has_many :burrito_ingredients
end

0512-burrito-upgrade-part-2/app/models/user.rb
require "bcrypt"
class User
  include Mongoid::Document
  field :name, type: String
  field :email, type: String
  field :password_digest, type: String

  def password
    @password
  end

  def password=(new_password)
    @password = new_password
    self.password_digest = BCrypt::Password.create(new_password)
  end

  def authenticate(test_password)
    if BCrypt::Password.new(self.password_digest) == test_password
      self
    else
      false
    end
  end
end

paul = User.new(name: "Paul" afsldkjf, password:"fsadfds")

paul.authenticate(params[:password])

0512-burrito-upgrade-part-2/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  include ApplicationHelper
end

0512-burrito-upgrade-part-2/app/controllers/burritos_controller.rb
class BurritosController < ApplicationController

  before_action :authenticate_user

  def index
    @burritos = Burrito.all
  end

  def show
    @burrito = Burrito.find(params[:id])
  end

  def new
    @burrito = Burrito.new
    @ingredients = Ingredient.all
  end

  def create
    Burrito.create(params.require(:burrito).permit(:name, :ingredient_ids => []))
    redirect_to burritos_path
  end

  def edit
    @burrito = Burrito.find(params[:id])
    @ingredients = Ingredient.all
  end

  def update
    @burrito = Burrito.find(params[:id])
    if @burrito.update(params.require(:burrito).permit(:name, :ingredient_ids => []))
      redirect_to burritos_path
    else
      render 'edit'
    end
  end

  def destroy
  end
end

0512-burrito-upgrade-part-2/app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
  end

  def create
    @user = User.where(:email => params[:session][:email]).first

    if @user == nil || !@user.authenticate(params[:session][:password])
      flash[:error] = "Invalid email/password combination"
      render 'new'
    else
      session[:remember_token] = @user.id
      @current_user = @user
      redirect_to root_path
    end

  end

  def destroy
    session.delete(:remember_token)
    redirect_to root_path
  end

end

0512-burrito-upgrade-part-2/app/controllers/users_controller.rb
class UsersController < ApplicationController
  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)
    if @user.save
      flash[:success] = "You have signed up successfully"
      redirect_to :root
    else
      render :new
    end
  end

  protected

  def user_params
    params.require(:user).permit(:name, :email, :password)
  end
end

0512-burrito-upgrade-part-2/app/helpers/application_helper.rb
module ApplicationHelper
	def current_user
  	@current_user ||= session[:remember_token] && User.find(session[:remember_token])
  end

  def authenticate_user
  	if !current_user
  		redirect_to new_sessions_path
  	end
  end
end

0512-burrito-upgrade-part-2/app/helpers/burritos_helper.rb
module BurritosHelper
end

0512-burrito-upgrade-part-2/app/helpers/sessions_helper.rb
module SessionsHelper
end

0512-burrito-upgrade-part-2/app/helpers/users_helper.rb
module UsersHelper
end

0512-burrito-upgrade-part-2/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>BurritoApp</title>
  <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
  <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
  <%= csrf_meta_tags %>
</head>
<body>
<nav class="navbar navbar-default navbar-fixed-top" role="navigation">
  <div class="container-fluid">
    <!-- Brand and toggle get grouped for better mobile display -->
    <div class="navbar-header">
      <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <a class="navbar-brand" href="#">Burritos for Everyone</a>
    </div>

    <!-- Collect the nav links, forms, and other content for toggling -->
    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
      <ul class="nav navbar-nav">
        <li><%= link_to "View Burritos", burritos_path %></li>
        <li><%= link_to "New Burrito", new_burrito_path %></li>
      </ul>
      <ul class="nav navbar-nav navbar-right">
        <% if !current_user %>
          <li><%= link_to "Sign Up", new_user_path %></li>
          <li><%= link_to "Sign In", new_sessions_path %></li>
        <% else %>
          <li><%= link_to "Sign Out", sessions_path, :method => :delete %></li>
        <% end %>
      </ul>
    </div><!-- /.navbar-collapse -->
  </div><!-- /.container-fluid -->
</nav>
<div class="container-fluid">
  <% flash.each do |key, value| %>
    <div class="alert alert-<%= key %>"><%= value %></div>
  <% end %>
  <%= yield %>
</div>

</body>
</html>