0430-rails_app/breweries/config/routes.rb
Rails.application.routes.draw do
  resources :breweries

  get 'beers/' => 'beers#index'
  get 'beers/new' => 'beers#new', as: :beers_new
  post 'beers/' => 'beers#create'
  get 'beers/:id' => 'beers#show', as: :beer
  get 'beers/:id/edit' => 'beers#edit', as: :edit_beer
  patch 'beers/:id' => 'beers#update'
  delete 'beers/:id' => 'beers#destroy'

end

0430-rails_app/breweries/app/models/beer.rb
class Beer
  include Mongoid::Document
  include Mongoid::Timestamps
  field :name, type: String
  field :type, type: String
  field :brewer, type: String
  field :abv, type: Float
end

0430-rails_app/breweries/app/models/brewery.rb
class Brewery
  include Mongoid::Document
  field :name, type: String
  field :city, type: String
  field :state, type: String
end

0430-rails_app/breweries/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

0430-rails_app/breweries/app/controllers/beers_controller.rb
class BeersController < ApplicationController
	before_action :set_beer, only: [:edit, :update, :show, :destroy]

	def index
		@beers = Beer.all
	end

	def new
		@beer = Beer.new
	end

	def create
		@beer = Beer.new(params.require(:beer).permit(:name, :type, :brewer, :abv))
		if @beer.save
			redirect_to beers_path
		else
			render 'new'
		end
	end

	def show
	end

	def edit
	end

	def update
		if @beer.update_attributes(params.require(:beer).permit(:name, :type, :brewer, :abv))
			redirect_to beers_path
		else
			render 'edit'
		end
	end

	def destroy
		@beer.destroy
		redirect_to beers_path
	end


	private 
	def set_beer
		@beer = Beer.find(params[:id])
	end

end

0430-rails_app/breweries/app/controllers/breweries_controller.rb
class BreweriesController < ApplicationController
  before_action :set_brewery, only: [:show, :edit, :update, :destroy]

  # GET /breweries
  # GET /breweries.json
  def index
    @breweries = Brewery.all
  end

  # GET /breweries/1
  # GET /breweries/1.json
  def show
  end

  # GET /breweries/new
  def new
    @brewery = Brewery.new
  end

  # GET /breweries/1/edit
  def edit
  end

  # POST /breweries
  # POST /breweries.json
  def create
    @brewery = Brewery.new(brewery_params)

    respond_to do |format|
      if @brewery.save
        format.html { redirect_to @brewery, notice: 'Brewery was successfully created.' }
        format.json { render :show, status: :created, location: @brewery }
      else
        format.html { render :new }
        format.json { render json: @brewery.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /breweries/1
  # PATCH/PUT /breweries/1.json
  def update
    respond_to do |format|
      if @brewery.update(brewery_params)
        format.html { redirect_to @brewery, notice: 'Brewery was successfully updated.' }
        format.json { render :show, status: :ok, location: @brewery }
      else
        format.html { render :edit }
        format.json { render json: @brewery.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /breweries/1
  # DELETE /breweries/1.json
  def destroy
    @brewery.destroy
    respond_to do |format|
      format.html { redirect_to breweries_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_brewery
      @brewery = Brewery.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def brewery_params
      params.require(:brewery).permit(:name, :city, :state)
    end
end

0430-rails_app/breweries/app/helpers/application_helper.rb
module ApplicationHelper
end

0430-rails_app/breweries/app/helpers/beers_helper.rb
module BeersHelper
end

0430-rails_app/breweries/app/helpers/breweries_helper.rb
module BreweriesHelper
end

0430-rails_app/breweries/app/views/beers/_form.html.erb
<%= form_for(@beer) do |f| %>

	Name: <%= f.text_field :name %>
	Type: <%= f.text_field :type %>
	Brewer: <%= f.text_field :brewer %>
	ABV: <%= f.text_field :abv %> 

	<%= f.submit "Add a new beer!" %>

<%end%>

0430-rails_app/breweries/app/views/beers/edit.html.erb
<h1>Edit a beer!</h1>

<%= render 'form' %>

<%= link_to "Go back to the list!", beers_path %>

0430-rails_app/breweries/app/views/beers/index.html.erb
<h1>These are Beers</h1>

<% @beers.each do |b| %>
	<p>I'm drinking <%= b.name %> by <%= b.brewer %> <%= link_to "Details", b %></p>

<% end %>

<%= link_to "Create a new beer", beers_new_path %>

0430-rails_app/breweries/app/views/beers/new.html.erb
<h1>Make a new beer!</h1>

<%= render 'form' %>

<%= link_to "Go back to the list!", beers_path %>

0430-rails_app/breweries/app/views/beers/show.html.erb
<h1>Beer!</h1>

<%= @beer.name %> is awesome!

<%= link_to "Edit Beer", edit_beer_path %>
<%= link_to "Delete this Beer", @book, method: :delete, data: { confirm: 'Are you sure you want to delete this?' } %>
<%= link_to "Back to the list", beers_path %>

0430-rails_app/breweries/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Breweries</title>
  <%= stylesheet_link_tag    'application', media: 'all' %>
  <%= javascript_include_tag 'application' %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>