0515-rb-tunes/config/routes.rb
RbTunes::Application.routes.draw do
  resources :playlists do
    resources :songs, :only => [:create, :destroy], :controller => 'playlists_songs'
  end

  resources :albums do
    resources :songs, :only => [:create, :destroy], :controller => 'albums_songs'
  end

  resources :artists do 
    resources :songs, :only => [:new, :create, :edit, :update], :controller => 'albums_songs'
  end

  get "welcome/index"

  resources :songs

  get 'welcome/index'

  root :to => 'welcome#index'

end

0515-rb-tunes/app/models/artist.rb
class Artist
  include Mongoid::Document
  include Mongoid::Timestamps

  field :name, type: String
  field :genre, type: String

  has_many :albums
  has_many :songs

end

0515-rb-tunes/app/controllers/artists_controller.rb
class ArtistsController < ApplicationController
  # GET /artists
  # GET /artists.json
  def index
    @artists = Artist.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @artists }
    end
  end

  # GET /artists/1
  # GET /artists/1.json
  def show
    @artist = Artist.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @artist }
    end
  end

  # GET /artists/new
  # GET /artists/new.json
  def new
    @artist = Artist.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @artist }
    end
  end

  # GET /artists/1/edit
  def edit
    @artist = Artist.find(params[:id])
  end

  # POST /artists
  # POST /artists.json
  def create
    @artist = Artist.new(artist_params)

    respond_to do |format|
      if @artist.save
        format.html { redirect_to @artist, notice: 'Artist was successfully created.' }
        format.json { render json: @artist, status: :created, location: @artist }
      else
        format.html { render action: "new" }
        format.json { render json: @artist.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /artists/1
  # PUT /artists/1.json
  def update
    @artist = Artist.find(params[:id])

    respond_to do |format|
      if @artist.update_attributes(artist_params)
        format.html { redirect_to @artist, notice: 'Artist was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @artist.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /artists/1
  # DELETE /artists/1.json
  def destroy
    @artist = Artist.find(params[:id])
    @artist.destroy

    respond_to do |format|
      format.html { redirect_to artists_url }
      format.json { head :no_content }
    end
  end

  protected

  def artist_params
    params.require(:artist).permit(:name, :genre)
  end
end

0515-rb-tunes/app/helpers/artists_helper.rb
module ArtistsHelper
end

0515-rb-tunes/app/views/artists/_form.html.erb
<%= form_for(@artist) do |f| %>
  <% if @artist.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@artist.errors.count, "error") %> prohibited this artist from being saved:</h2>

      <ul>
      <% @artist.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br />
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :genre %><br />
    <%= f.text_field :genre %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

0515-rb-tunes/app/views/artists/edit.html.erb
<h1>Editing artist</h1>

<%= render 'form' %>

<%= link_to 'Show', @artist %> |
<%= link_to 'Back', artists_path %>

0515-rb-tunes/app/views/artists/index.html.erb
<h1>Artists</h1>

<table class="table">
  <thead>
    <tr>
      <th>Name</th>
      <th>Genre</th>
      <th></th>
      <th></th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% @artists.each do |artist| %>
      <tr>
        <td><%= artist.name %></td>
        <td><%= artist.genre %></td>
        <td><%= link_to 'View', artist %></td>
        <td><%= link_to 'Edit', edit_artist_path(artist) %></td>
        <td><%= link_to 'Delete', artist, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br />

<%= link_to 'New Artist', new_artist_path %>

0515-rb-tunes/app/views/artists/new.html.erb
<h1>New artist</h1>

<%= render 'form' %>

<%= link_to 'Back', artists_path %>

0515-rb-tunes/app/views/artists/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Name:</b>
  <%= @artist.name %>
</p>

<p>
  <b>Genre:</b>
  <%= @artist.genre %>
</p>

<div class="artist-songs">
  <h3>Songs</h3>
  <%= render :partial => 'shared/short_song_list', :locals => {:songs => @artist.songs } %>
</div>

<div class="artist-albums">
  <h3>Albums</h3>
  <%= render :partial => 'shared/short_album_list', :locals => {:albums => @artist.albums } %>
</div>

<%= link_to 'Edit', edit_artist_path(@artist) %> |
<%= link_to 'Back', artists_path %>